import { env } from "cloudflare:workers";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const COOKIE = "points_session";
const DAYS = 30;
export type SessionMember = { id:number;authUserId:string;email:string;displayName:string;status:string;role:string;startingBalance:number;balance:number;rebuyCount:number;emailVerifiedAt:string|null };
const values=()=>env as unknown as Record<string,string|undefined>;
export const isSameOrigin=(request:Request)=>{const origin=request.headers.get("origin");try{return !!origin&&new URL(origin).origin===new URL(request.url).origin;}catch{return false;}};
export const safeReturnTo=(value:string|null|undefined)=>{if(!value||!value.startsWith("/")||value.startsWith("//"))return "/";try{const url=new URL(value,"https://points.local");return url.origin==="https://points.local"&&!url.pathname.startsWith("/api/")&&url.pathname!=="/login"?`${url.pathname}${url.search}${url.hash}`:"/";}catch{return "/";}};
export const loginPath=(returnTo="/")=>`/login?returnTo=${encodeURIComponent(safeReturnTo(returnTo))}`;
export async function requestEmailCode(email:string){const v=values();if(!v.SUPABASE_URL||!v.SUPABASE_PUBLISHABLE_KEY)throw new Error("Email sign-in is not configured.");const r=await fetch(`${v.SUPABASE_URL}/auth/v1/otp`,{method:"POST",headers:{apikey:v.SUPABASE_PUBLISHABLE_KEY,"content-type":"application/json"},body:JSON.stringify({email,create_user:true})});if(!r.ok){const b=await r.json().catch(()=>({})) as {msg?:string;error_description?:string};throw new Error(b.msg??b.error_description??"The sign-in code could not be sent.");}}
export async function verifyEmailCode(email:string,token:string){const v=values();if(!v.SUPABASE_URL||!v.SUPABASE_PUBLISHABLE_KEY)throw new Error("Email sign-in is not configured.");const r=await fetch(`${v.SUPABASE_URL}/auth/v1/verify`,{method:"POST",headers:{apikey:v.SUPABASE_PUBLISHABLE_KEY,"content-type":"application/json"},body:JSON.stringify({email,token,type:"email"})});const b=await r.json().catch(()=>({})) as {user?:{id?:string;email?:string;email_confirmed_at?:string};msg?:string;error_description?:string};if(!r.ok||!b.user?.id||!b.user.email||!b.user.email_confirmed_at)throw new Error(b.msg??b.error_description??"That code is invalid or expired.");return b.user as {id:string;email:string;email_confirmed_at:string};}
const bytesToBase64Url=(bytes:Uint8Array)=>{let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");};
async function hash(value:string){return bytesToBase64Url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))));}
export async function createMemberSession(memberId:number){const token=bytesToBase64Url(crypto.getRandomValues(new Uint8Array(32)));const expiresAt=new Date(Date.now()+DAYS*86400000).toISOString();await env.DB.prepare("INSERT INTO auth_sessions (member_id,token_hash,expires_at) VALUES (?,?,?)").bind(memberId,await hash(token),expiresAt).run();return token;}
export function sessionCookie(token:string,requestUrl:string){return [`${COOKIE}=${encodeURIComponent(token)}`,"Path=/","HttpOnly","SameSite=Lax",new URL(requestUrl).protocol==="https:"?"Secure":"",`Max-Age=${DAYS*86400}`].filter(Boolean).join("; ");}
export function clearedSessionCookie(requestUrl:string){return [`${COOKIE}=`,"Path=/","HttpOnly","SameSite=Lax",new URL(requestUrl).protocol==="https:"?"Secure":"","Max-Age=0"].filter(Boolean).join("; ");}
export async function getSessionMember():Promise<SessionMember|null>{const token=(await cookies()).get(COOKIE)?.value;if(!token)return null;return await env.DB.prepare("SELECT m.id,m.auth_user_id AS authUserId,m.email,m.display_name AS displayName,m.status,m.role,m.starting_balance AS startingBalance,m.balance,m.rebuy_count AS rebuyCount,m.email_verified_at AS emailVerifiedAt FROM auth_sessions s JOIN members m ON m.id=s.member_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND datetime(s.expires_at)>CURRENT_TIMESTAMP").bind(await hash(token)).first<SessionMember>()??null;}
export async function requireSessionMember(returnTo="/portal"){const member=await getSessionMember();if(member)return member;redirect(loginPath(returnTo));}
export async function revokeCurrentSession(){const token=(await cookies()).get(COOKIE)?.value;if(token)await env.DB.prepare("UPDATE auth_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE token_hash=? AND revoked_at IS NULL").bind(await hash(token)).run();}
