import { env } from "cloudflare:workers";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const COOKIE = "points_session";
const DAYS = 30;
export type SessionMember = { id:number;authUserId:string;email:string;displayName:string;status:string;role:string;startingBalance:number;balance:number;rebuyCount:number;emailVerifiedAt:string|null;createdAt:string };
const values=()=>env as unknown as Record<string,string|undefined>;
export const isSameOrigin=(request:Request)=>{const origin=request.headers.get("origin");try{return !!origin&&new URL(origin).origin===new URL(request.url).origin;}catch{return false;}};
export const safeReturnTo=(value:string|null|undefined)=>{if(!value||!value.startsWith("/")||value.startsWith("//"))return "/";try{const url=new URL(value,"https://points.local");return url.origin==="https://points.local"&&!url.pathname.startsWith("/api/")&&url.pathname!=="/login"?`${url.pathname}${url.search}${url.hash}`:"/";}catch{return "/";}};
export const loginPath=(returnTo="/")=>`/login?returnTo=${encodeURIComponent(safeReturnTo(returnTo))}`;
type SupabaseUser={id?:string;email?:string;email_confirmed_at?:string;user_metadata?:{username?:string}};
const authError=async(r:Response,fallback:string)=>{const body=await r.json().catch(()=>({})) as {msg?:string;error_description?:string;message?:string};return body.msg??body.error_description??body.message??fallback;};
export async function registerWithPassword(email:string,password:string,username:string){const v=values();if(!v.SUPABASE_URL||!v.SUPABASE_PUBLISHABLE_KEY)throw new Error("Account registration is not configured.");const r=await fetch(`${v.SUPABASE_URL}/auth/v1/signup`,{method:"POST",headers:{apikey:v.SUPABASE_PUBLISHABLE_KEY,"content-type":"application/json"},body:JSON.stringify({email,password,data:{username}})});if(!r.ok)throw new Error(await authError(r,"We could not create that account."));}
export async function signInWithPassword(email:string,password:string){const v=values();if(!v.SUPABASE_URL||!v.SUPABASE_PUBLISHABLE_KEY)throw new Error("Account sign-in is not configured.");const r=await fetch(`${v.SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:v.SUPABASE_PUBLISHABLE_KEY,"content-type":"application/json"},body:JSON.stringify({email,password})});const body=await r.json().catch(()=>({})) as {user?:SupabaseUser;msg?:string;error_description?:string;message?:string};if(!r.ok)throw new Error(body.msg??body.error_description??body.message??"Email or password is incorrect.");if(!body.user?.id||!body.user.email||!body.user.email_confirmed_at)throw new Error("Confirm your email before signing in.");return body.user as Required<Pick<SupabaseUser,"id"|"email"|"email_confirmed_at">>&SupabaseUser;}
export async function resendSignupConfirmation(email:string){const v=values();if(!v.SUPABASE_URL||!v.SUPABASE_PUBLISHABLE_KEY)throw new Error("Email confirmation is not configured.");const r=await fetch(`${v.SUPABASE_URL}/auth/v1/resend`,{method:"POST",headers:{apikey:v.SUPABASE_PUBLISHABLE_KEY,"content-type":"application/json"},body:JSON.stringify({type:"signup",email})});if(!r.ok)throw new Error(await authError(r,"We could not resend that email."));}
export async function requestPasswordReset(email:string){const v=values();if(!v.SUPABASE_URL||!v.SUPABASE_PUBLISHABLE_KEY||!v.SITE_PUBLIC_URL)throw new Error("Password reset is not configured.");const r=await fetch(`${v.SUPABASE_URL}/auth/v1/recover`,{method:"POST",headers:{apikey:v.SUPABASE_PUBLISHABLE_KEY,"content-type":"application/json"},body:JSON.stringify({email,redirect_to:`${v.SITE_PUBLIC_URL.replace(/\/$/,"")}/reset-password`})});if(!r.ok)throw new Error(await authError(r,"We could not send a reset email."));}
export async function updatePassword(accessToken:string,password:string){const v=values();if(!v.SUPABASE_URL||!v.SUPABASE_PUBLISHABLE_KEY)throw new Error("Password reset is not configured.");const r=await fetch(`${v.SUPABASE_URL}/auth/v1/user`,{method:"PUT",headers:{apikey:v.SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${accessToken}`,"content-type":"application/json"},body:JSON.stringify({password})});const body=await r.json().catch(()=>({})) as {email?:string;msg?:string;error_description?:string;message?:string};if(!r.ok||!body.email)throw new Error(body.msg??body.error_description??body.message??"That reset link is invalid or expired.");await env.DB.prepare("UPDATE auth_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE member_id IN (SELECT id FROM members WHERE email=?) AND revoked_at IS NULL").bind(body.email.toLowerCase()).run();return body.email;}
const bytesToBase64Url=(bytes:Uint8Array)=>{let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");};
async function hash(value:string){return bytesToBase64Url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))));}
export async function createMemberSession(memberId:number){const token=bytesToBase64Url(crypto.getRandomValues(new Uint8Array(32)));const expiresAt=new Date(Date.now()+DAYS*86400000).toISOString();await env.DB.prepare("INSERT INTO auth_sessions (member_id,token_hash,expires_at) VALUES (?,?,?)").bind(memberId,await hash(token),expiresAt).run();return token;}
export function sessionCookie(token:string,requestUrl:string){return [`${COOKIE}=${encodeURIComponent(token)}`,"Path=/","HttpOnly","SameSite=Lax",new URL(requestUrl).protocol==="https:"?"Secure":"",`Max-Age=${DAYS*86400}`].filter(Boolean).join("; ");}
export function clearedSessionCookie(requestUrl:string){return [`${COOKIE}=`,"Path=/","HttpOnly","SameSite=Lax",new URL(requestUrl).protocol==="https:"?"Secure":"","Max-Age=0"].filter(Boolean).join("; ");}
export async function getSessionMember():Promise<SessionMember|null>{const token=(await cookies()).get(COOKIE)?.value;if(!token)return null;return await env.DB.prepare("SELECT m.id,m.auth_user_id AS authUserId,m.email,m.display_name AS displayName,m.status,m.role,m.starting_balance AS startingBalance,m.balance,m.rebuy_count AS rebuyCount,m.email_verified_at AS emailVerifiedAt,m.created_at AS createdAt FROM auth_sessions s JOIN members m ON m.id=s.member_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND datetime(s.expires_at)>CURRENT_TIMESTAMP").bind(await hash(token)).first<SessionMember>()??null;}
export async function requireSessionMember(returnTo="/portal"){const member=await getSessionMember();if(member)return member;redirect(loginPath(returnTo));}
export async function revokeCurrentSession(){const token=(await cookies()).get(COOKIE)?.value;if(token)await env.DB.prepare("UPDATE auth_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE token_hash=? AND revoked_at IS NULL").bind(await hash(token)).run();}
