"use client";
import { useState } from "react";
import type { LeagueSettings } from "../lib/league-config";

type Member = { id:number;email:string;displayName:string;status:string;role:string;startingBalance:number;balance:number;emailVerifiedAt:string|null;createdAt:string };
type Wager = { id:number;playerKey:string;betType:string;stake:number;status:string;payout:number|null;gradingReason:string|null;placedAt:string;settledAt:string|null };
type Sync = { league:string;lastSuccessAt:string|null;creditsRemaining:number|null;lastError:string|null };
type AuditEvent={actorEmail:string|null;eventType:string;subjectType:string;subjectId:string|null;detailsJson:string|null;createdAt:string};

export function AdminPortal({ initialMembers, initialWagers, sync, initialSettings, initialAudit, emailConfigured }: { initialMembers:Member[];initialWagers:Wager[];sync:Sync[];initialSettings:LeagueSettings;initialAudit:AuditEvent[];emailConfigured:boolean }) {
  const [members,setMembers]=useState(initialMembers);const [wagers,setWagers]=useState(initialWagers);const [syncRows,setSyncRows]=useState(sync);const [message,setMessage]=useState("");const [refreshing,setRefreshing]=useState(false);const [savingSettings,setSavingSettings]=useState(false);const [sendingEmail,setSendingEmail]=useState(false);const [emailSubject,setEmailSubject]=useState("");const [emailBody,setEmailBody]=useState("");const [settingsText,setSettingsText]=useState(JSON.stringify(initialSettings,null,2));
  const updateMember=async(member:Member,patch:Partial<Member>)=>{setMessage("");const response=await fetch("/api/admin/members",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:member.id,...patch})});const body=await response.json() as {member?:Member;email?:{sent:boolean;error?:string};error?:string};if(response.ok&&body.member){setMembers(current=>current.map(item=>item.id===member.id?body.member!:item));if(patch.status==="approved")setMessage(body.email?.sent?`${member.displayName} was approved and emailed.`:`${member.displayName} was approved, but the email was not sent${body.email?.error?`: ${body.email.error}`:"."}`);}else setMessage(body.error??"Update failed.");};
  const refresh=async()=>{setRefreshing(true);setMessage("");try{const response=await fetch("/api/admin/sync",{method:"POST"});const body=await response.json().catch(()=>({error:"The refresh service returned an unreadable response."})) as {message?:string;error?:string;sync?:Sync[]};if(body.sync)setSyncRows(body.sync);setMessage(body.message??body.error??(response.ok?"Refresh finished.":"The refresh could not finish."));}catch{setMessage("The refresh request could not reach the service. Check your connection and try again.");}finally{setRefreshing(false);}};
  const saveSettings=async()=>{setSavingSettings(true);setMessage("");try{const settings=JSON.parse(settingsText) as LeagueSettings;const response=await fetch("/api/admin/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({settings})});const body=await response.json() as {settings?:LeagueSettings;error?:string};if(!response.ok||!body.settings)throw new Error(body.error??"Settings could not be saved.");setSettingsText(JSON.stringify(body.settings,null,2));setMessage("Season settings saved.");}catch(error){setMessage(error instanceof Error?error.message:"Settings could not be saved.");}finally{setSavingSettings(false);}};
  const sendLeagueEmail=async()=>{setSendingEmail(true);setMessage("");const response=await fetch("/api/admin/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({subject:emailSubject,message:emailBody})});const body=await response.json() as {sent?:number;total?:number;error?:string};if(response.ok){setMessage(`Email sent to ${body.sent} approved player${body.sent===1?"":"s"}.`);setEmailSubject("");setEmailBody("");}else setMessage(body.error??"The league email could not be sent.");setSendingEmail(false);};
  const voidWager=async(wager:Wager)=>{const reason=window.prompt(`Why is ticket #${String(wager.id).padStart(5,"0")} being voided?`);if(!reason)return;setMessage("");const response=await fetch("/api/admin/wagers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({wagerId:wager.id,reason})});const body=await response.json() as {error?:string};if(!response.ok){setMessage(body.error??"The ticket could not be voided.");return;}setWagers(current=>current.map(item=>item.id===wager.id?{...item,status:"void",payout:item.stake,gradingReason:reason,settledAt:new Date().toISOString()}:item));setMessage(`Ticket #${String(wager.id).padStart(5,"0")} was voided and the stake was returned.`);};
  const approved=members.filter(member=>member.status==="approved").length;const pending=members.filter(member=>member.status==="pending").length;
  return <div className="shell"><div className="admin-summary"><article><strong>{members.length}</strong><span>Total members</span></article><article><strong>{approved}</strong><span>Approved</span></article><article><strong>{pending}</strong><span>Pending</span></article><article><strong>{initialWagers.length}</strong><span>Wagers</span></article></div>
    <div className="portal-section-heading"><div><p className="eyebrow">SEASON CONTROL</p><h2>League settings</h2></div></div>
    <div className="season-settings"><textarea aria-label="Season settings JSON" value={settingsText} onChange={event=>setSettingsText(event.target.value)} spellCheck={false}/><div className="settings-actions"><p>Edit the season configuration directly. Invalid combinations will be rejected when you save.</p><button className="button button-primary" onClick={saveSettings} disabled={savingSettings}>{savingSettings?"Saving":"Save season settings"}</button></div></div>
    <div className="portal-section-heading"><div><p className="eyebrow">ODDS SERVICE</p><h2>Odds feed status</h2></div><button className="button button-primary" onClick={refresh} disabled={refreshing}>{refreshing?"Refreshing":"Refresh NFL + CFB"}</button></div>
    <div className="feed-cards">{(["nfl","cfb"]).map(league=>{const row=syncRows.find(item=>item.league===league);return <article key={league}><span className={`league-pill league-pill-${league}`}>{league}</span><strong>{row?.lastSuccessAt?new Date(row.lastSuccessAt).toLocaleString():"Waiting for first sync"}</strong><small>{row?.creditsRemaining==null?"Usage not reported":`${row.creditsRemaining.toLocaleString()} data points remaining`}</small>{row?.lastError&&<em>{row.lastError}</em>}</article>;})}</div>
    {message&&<div className="portal-notice">{message}</div>}
    <div className="portal-section-heading"><div><p className="eyebrow">LEAGUE EMAIL</p><h2>Email all players</h2></div><span className={`member-status status-${emailConfigured?"approved":"pending"}`}>{emailConfigured?"Email ready":"Email setup needed"}</span></div>
    <div className="league-email"><label><span>Subject</span><input value={emailSubject} onChange={event=>setEmailSubject(event.target.value)} maxLength={140} placeholder="Week 1 reminder" /></label><label><span>Message</span><textarea value={emailBody} onChange={event=>setEmailBody(event.target.value)} maxLength={10000} placeholder="Write your message to the league." /></label><div><p>Each approved player receives a separate email. Player addresses are never shared.</p><button className="button button-primary" onClick={sendLeagueEmail} disabled={sendingEmail||!emailConfigured||!emailSubject.trim()||!emailBody.trim()}>{sendingEmail?"Sending":`Email ${approved} approved player${approved===1?"":"s"}`}</button></div></div>
    <div className="portal-section-heading"><div><p className="eyebrow">ROSTER</p><h2>Member management</h2></div></div>
    <div className="portal-table-wrap"><table className="portal-table admin-members"><thead><tr><th>Member</th><th>Status</th><th>Role</th><th>Starting</th><th>Balance</th><th>Actions</th></tr></thead><tbody>{members.map(member=><tr key={member.id}><td><strong>{member.displayName}</strong><small>{member.email}</small><small>{member.emailVerifiedAt?"Verified":"Unverified"}</small></td><td><span className={`member-status status-${member.status}`}>{member.status}</span></td><td>{member.role}</td><td>{Number(member.startingBalance).toLocaleString()}</td><td><input aria-label={`${member.displayName} balance`} type="number" defaultValue={member.balance} onBlur={event=>{const value=Number(event.target.value);if(value!==member.balance)updateMember(member,{balance:value});}} /></td><td><div className="row-actions">{member.status!=="approved"&&member.emailVerifiedAt&&<button onClick={()=>updateMember(member,{status:"approved"})}>Approve</button>}{member.status==="approved"&&member.role!=="commissioner"&&<button onClick={()=>updateMember(member,{status:"suspended"})}>Suspend</button>}</div></td></tr>)}</tbody></table></div>
    <div className="portal-section-heading"><div><p className="eyebrow">WAGER LOG</p><h2>Recent wagers</h2></div></div>
    <div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Ticket</th><th>Player</th><th>Type</th><th>Stake</th><th>Status</th><th>Return</th><th>Placed</th><th>Action</th></tr></thead><tbody>{wagers.length?wagers.map(wager=><tr key={wager.id}><td>#{String(wager.id).padStart(5,"0")}</td><td>{wager.playerKey}</td><td>{wager.betType}</td><td>{Number(wager.stake).toLocaleString()}</td><td><span className={`ticket-status ticket-${wager.status}`}>{wager.status}</span></td><td>{wager.payout==null?"—":Number(wager.payout).toLocaleString()}</td><td>{new Date(wager.placedAt).toLocaleString()}</td><td>{wager.status!=="void"?<button className="table-action" onClick={()=>voidWager(wager)}>Void ticket</button>:<small>{wager.gradingReason??"Voided"}</small>}</td></tr>):<tr><td colSpan={8}>No wagers have been placed.</td></tr>}</tbody></table></div>
    <div className="portal-section-heading"><div><p className="eyebrow">AUDIT LOG</p><h2>Commissioner activity</h2></div></div>
    <div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>When</th><th>Action</th><th>Subject</th><th>By</th></tr></thead><tbody>{initialAudit.length?initialAudit.map((event,index)=><tr key={`${event.createdAt}-${index}`}><td>{new Date(event.createdAt).toLocaleString()}</td><td>{event.eventType.replaceAll("_"," ")}</td><td>{event.subjectType}{event.subjectId?` #${event.subjectId}`:""}</td><td>{event.actorEmail??"System"}</td></tr>):<tr><td colSpan={4}>No commissioner activity this season.</td></tr>}</tbody></table></div>
  </div>;
}
